AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB Tables for Fondo API

Resources:

  ClientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: clients
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: clientId
          AttributeType: S
      KeySchema:
        - AttributeName: clientId
          KeyType: HASH

  SubscriptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: subscriptions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: clientId
          AttributeType: S
        - AttributeName: fundId
          AttributeType: S
      KeySchema:
        - AttributeName: clientId
          KeyType: HASH
        - AttributeName: fundId
          KeyType: RANGE

  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: transactions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: clientId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: clientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE