plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.12-SNAPSHOT'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.thinkus'
version = '0.0.1-SNAPSHOT'
description = 'Prueba desarrollador Java/AWS'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
	maven { url = 'https://repo.spring.io/snapshot' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'

	implementation platform('software.amazon.awssdk:bom:2.25.28')

	implementation 'software.amazon.awssdk:dynamodb'
	implementation 'software.amazon.awssdk:auth'
	implementation 'software.amazon.awssdk:regions'

	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.mockito:mockito-core'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}
